### PR TITLE
Adding support for Fedora 38

### LINKED ISSUE #109: Add support to package_build.py for Fedora 38
Update bin/package_build.py and to add support for the latest release of Fedora, 38.

### PR DESCRIPTION
**Pull request by xtanion**
Fixes #109

### CODE REVIEW

**Comment by arshPratap** [comment]
@xtanion please mention the issue you are trying to fix in the PR.. This makes it easier for us to keep a track for the said issues.. Anyways seems to be an authentication issue with your mail account and github account

**Comment by xtanion** [comment]
Hi @arshPratap. I updated the description, PTAL.
Thanks.

**Comment by pleia2** [comment]
Thanks for your work on this! The DCO check is a requirement for all Open Mainframe Project projects, here's how to fix the test: https://github.com/openmainframeproject/software-discovery-tool/pull/113/checks?check_run_id=13464508729

In the future, you can use the following on the command line when doing your commit to avoid this: git commit -a --signoff

**Comment by xtanion** [comment]
Done @pleia2, PTAL
Thanks

**Review by pleia2 — APPROVED** [review]

**Pull request merged**
