### PR TITLE
rocky version fixed from 9.0 to 9

### PR DESCRIPTION
**Pull request by aashish-khatri**
I've updated the rocky linux api link as requested in issue #103, I would like to know your thoughts on this @arshPratap @pleia2.

### CODE REVIEW

**Comment by arshPratap** [comment]
Lgtm

**Comment by pleia2** [comment]
Open Mainframe Project projects require DCO sign-off in the commit message, there are instructions on how to fix it here: https://github.com/openmainframeproject/software-discovery-tool/pull/112/checks?check_run_id=13464348220

And to avoid it in the future, when you commit your code you should use: git commit -a --signoff

**Comment by pleia2** [comment]
Oops, looks like it got a bit tangled up with the z/OS open tools work. You might want to create branches in git for each issue you're working on (for example: git checkout -b issue/103).

Can you re-create this pull request with just the Rocky Linux 9 change?

**Comment by aashish-khatri** [comment]
Yeah, actually, I forgot to switch the branch for the new issue and committed to this branch. I will re-create the PR.

**Comment by aashish-khatri** [comment]
@arshPratap @pleia2 I've corrected the pull requested. PTAL. I think the changes are right now.

**Review by arshPratap — APPROVED** [review]

**Comment by arshPratap** [comment]
LGTM !
Thanks @aashish-khatri

**Review by pleia2 — APPROVED** [review]

**Pull request merged**
