### PR TITLE
submodule update, automate scrip add and PDS data source instruction in instructions doc

### PR DESCRIPTION
**Pull request by rachejazz**
Signed-off-by: rachejazz <divyadeepti2000@gmail.com>

### CODE REVIEW

**Comment by rachejazz** [comment]
Preview:

#### Using data from PDS
For example, taking RHEL_8_Package_List.json, SUSE_Package_Hub_SLES_15.json and Ubuntu_21_04_Package_List.json
- create a file listing all the needed files
```
$cat distro_list
RHEL_8_Package_List.json
SUSE_Package_Hub_SLES_15.json
Ubuntu_21_04_Package_List.json
```
- format each line with starting `https://raw.githubusercontent.com/linux-on-ibm-z/PDS/master/distro_data/`
```
$cat distro_list
https://raw.githubusercontent.com/linux-on-ibm-z/PDS/master/distro_data/RHEL_8_Package_List.json
https://raw.githubusercontent.com/linux-on-ibm-z/PDS/master/distro_data/SUSE_Package_Hub_SLES_15.json
https://raw.githubusercontent.com/linux-on-ibm-z/PDS/master/distro_data/Ubuntu_21_04_Package_List.json
```
- `curl` the latest json files
```
while read -r line; do curl -o `echo $line | cut -f 8 -d "/"` $line; done < distro_list

**Comment by rachejazz** [comment]
Since the end goal of  sdt also has an API, I'll see if i can take data from pds in that way or not

**Comment by rachejazz** [comment]
Preview:


### Step 5: Cloning Data Directory (Only First Time)
 openmainframeproject/software-discovery-tool-data contains all OMP created json files. To add the data files, we will use `git submodule`
- map the submodule directory with the directory path and update the directory:
```
git submodule init && git submodule update
```
- since we cloned a new repo as root just now, give the permissions to `apache` user like we did before:
```
sudo chown -R apache:apache /opt/software-discovery-tool/distro_data
```

#### Updating Data Directory
Everytime there's an upstream change in the submodule:
- To update the data directory with the main repo with the remote changes:
```
git pull <upstream remote> <default branch> --submodule-recursive
```
- To update ONLY the data directory keeping the main repo as it is:
```
git submodule update --recursive --remote
```

#### Using data from PDS
For example, taking RHEL_8_Package_List.json
- Usage help will be displayed:
```
cd /opt/software-discovery-tool/distro_data/distro_data
./package_build
Usage:
./package_build <exact_file_name.json>
			[if data is from PDS]
./package_build debian
			[if data is from Debian]
./package_build
			[for displaying this help]
Example:
./package_build RHEL_8_Package_List.json
```
Example of extracting the RHEL_8_Package_List.json from PDS repo:
```
./package_build RHEL_8_Package_List.json
Extracting RHEL_8_Package_List.json from PDS data ...
Thanks for using SDT!
```
Make sure the json file exists in the PDS data directory.

**Comment by pleia2** [comment]
You can add the package_build script to this PR if you want. I recommend creating a top-level bin/ directory to put this in. And since some operating systems are picky about file extensions, let's call it package_build**.py** and update the documentation accordingly.

**Review by pleia2 — APPROVED** [review]

**Pull request merged**
